# Generated by Django 4.2.1 on 2023-05-14 02:43

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=256, null=True, verbose_name='作者')),
                ('organ', models.CharField(blank=True, max_length=256, null=True, verbose_name='学院')),
                ('source', models.CharField(blank=True, max_length=256, null=True, verbose_name='来源')),
                ('keywords', models.CharField(blank=True, max_length=256, null=True, verbose_name='关键词')),
                ('pub_time', models.CharField(blank=True, max_length=256, null=True, verbose_name='时间')),
                ('first_duty', models.CharField(blank=True, max_length=256, null=True, verbose_name='一作')),
                ('fund', models.CharField(blank=True, max_length=256, null=True, verbose_name='详细介绍')),
            ],
            options={
                'verbose_name_plural': '文章数据',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号')),
                ('addr', models.CharField(blank=True, max_length=8, null=True, verbose_name='用户地址信息')),
                ('name', models.CharField(blank=True, max_length=8, null=True, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, max_length=2, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='用户年龄')),
                ('role', models.CharField(default='普通用户', max_length=16, verbose_name='用户身份')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
